import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {WiDaySunny} from 'react-icons/wi'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, AiFillInstagram} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../../public/happyme.png'
import design from '../../public/design.png'
import code from '../../public/code.png'
import consulting from '../../public/consulting.png'
import web1 from '../../public/web1.png'
import web2 from '../../public/web2.png'
import web3 from '../../public/web3.png'
import web4 from '../../public/web4.png'
import web5 from '../../public/web5.png'
import web6 from '../../public/web6.png'
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My PortiFolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={(darkMode) ? 'bg-white px-10 md:px-20 lg:px-40  dark:bg-gradient-to-b from-gray-800 to-black' : 'bg-gradient-to-b from-white to-teal-50 px-10 md:px-20 lg:px-40'}>
        <section className='min-h-screen' >
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-gray-300' >developedbyBusquet</h1>
            <ul className='flex items-center '>
              <li>
                <div>
                  { (!darkMode) ? <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='themeicon cursor-pointer text-1xl hover:text-2xl' /> : <WiDaySunny onClick={() => setDarkMode(!darkMode)} className='themeicon cursor-pointer font-bold text-2xl text-gray-300 hover:text-3xl' /> }
                </div>
              </li>
              <li>
                <a href="#description" className='resume__button bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2  rounded-md ml-8'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Raphael Busquet</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-500' >Web Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>
              Hey guys! Welcome to my own site. That's the first site I've created for my portifolio. 
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://twitter.com/Raphaelbusquet" target='_blank'>
              <AiFillTwitterCircle />
            </a>
            <a href="https://www.linkedin.com/in/raphaelbusquet/" target='_blank'>
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/raphaelbusquet/" target='_blank'>
              <AiFillInstagram />
            </a>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mb-10  overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} fill style='background-image: cover;' />
          </div>
        </section>
        <section>
          <div>
            <h3 id='description' className='text-3xl py-1 dark:text-gray-300'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>

              Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio saepe explicabo aspernatur, vero illum inventore veniam maxime, quos ad deserunt maiores doloremque delectus incidunt exercitationem quidem assumenda voluptas, fugit labore?
              <br />
              <span className='text-teal-500'>Lorem</span> ipsum dolor sit amet consectetur adipisicing elit. Ex nulla rem, labore repellendus dicta non enim provident? Eaque nam vel qui, corrupti, soluta <span className='text-teal-500'>consequatur</span> iusto ducimus quaerat eum, quasi laudantium?

            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='bg-white text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-300'>
              <Image src={design} width={100} height={100} className='m-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2 '>
                <br />
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, dignissimos a officiis ratione aspernatur eveniet autem ex, placeat recusandae repellat delectus optio corporis earum soluta unde at aliquam itaque quidem.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1'>Photoshop</p>
                <p className='text-gray-800 py-1'>Ilustrator</p>
                <p className='text-gray-800 py-1'>Figma</p>        
            </div>

            <div className=' bg-white text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-300'>
              <Image src={code} width={100} height={100} className='m-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Clean Code</h3>
              <p className='py-2 '>
                <br />
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, dignissimos a officiis ratione aspernatur eveniet autem ex, placeat recusandae repellat delectus optio corporis earum soluta unde at aliquam itaque quidem.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1'>Next.js</p>
                <p className='text-gray-800 py-1'>Css3</p>
                <p className='text-gray-800 py-1'>TailWindCss</p>        
            </div>

            <div className='bg-white text-center shadow-lg p-10 rounded-xl my-10  dark:bg-gray-300 dark:shadow-lg '>
              <Image src={consulting} width={100} height={100} className='m-auto' />
              <h3 className='text-lg font-medium pt-8 pb-2'>Seo Friendly</h3>
              <p className='py-2 '>
                <br />
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, dignissimos a officiis ratione aspernatur eveniet autem ex, placeat recusandae repellat delectus optio corporis earum soluta unde at aliquam itaque quidem.</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className='text-gray-800 py-1'>Google Analytics</p>
                <p className='text-gray-800 py-1'>Seo Search Tool</p>
                <p className='text-gray-800 py-1'>Seo Master</p>        
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 leading-8 text-gray-800  dark:text-gray-300'>Portofolio</h3>
            <br />
            <p className=' dark:text-gray-300'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere error beatae, quidem magni amet voluptatibus natus minus obcaecati quae <span className='text-teal-500'>accusamus</span> labore consequatur eius omnis P? Perferendis, fugit? Expedita, reiciendis porro.
              br
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque fuga itaque rem placeat <span className='text-teal-500'>repellendus</span>! Ipsam reiciendis culpa reprehenderit impedit, cum laudantium magni, voluptas blanditiis alias, excepturi facere consectetur nemo quaerat.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>          
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
            </div>
          </div>
        </section>
      </main>
      <footer  className='bg-teal-50 p-5 font-medium flex justify-center italic dark:bg-black  dark:text-gray-300'>
        <p>Created by&nbsp;</p> <span><a href="https://www.instagram.com/raphaelbusquet">@raphaelbusquet</a></span>
      </footer>
    </div>
  )
}
